### PR TITLE
Refresh Java staging clients with latest toolkit

### PR DESCRIPTION
**Pull request by shinfan**
Update to GAX 0.7.0 with the `PropertiesProvider` Change.

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Could we update PubSub and the header version separately from each other? @michaelbausor and @neozwu were working on updating PubSub.

**Comment by michaelbausor** [comment]
@garrettjonesgoogle We got to the point of regenerating core protos, but found that there was an error with the packman generation (missing some protos). Rather than invest effort to debug and fix, we discussed with @shinfan and decided to wait until https://github.com/googleapis/artman/pull/143 is merged, and then can regenerate without packman.

**Comment by michaelbausor** [comment]
We could submit the pubsub regeneration with its own version bump but without republishing all other proto packages as @shinfan has done here, except it is own PR.

**Comment by garrettjonesgoogle** [comment]
I think the 0.1.6 version of grpc-google-cloud-pubsub-v1 might have been generated from the latest protos already.

**Comment by shinfan** [comment]
Conflicts resolved. PTAL

**Comment by garrettjonesgoogle** [comment]
LGTM

**Comment by michaelbausor** [comment]
LGTM

**Pull request merged**
