### PR TITLE
Generate Python Monitoring using 0.14.0 codegen

### PR DESCRIPTION
**Pull request by bjwatson**
This PR is dependent on https://github.com/googleapis/api-client-staging/pull/146 (a simple test code reorg) being merged first.

@ethanbao Can you review what I did with your Python Monitoring tests? I figured it was time to get them out of my email and into Github.

@lukesneeringer @geigerj Please review my updates to the Monitoring gRPC and GAPIC packages. The system tests did not work with the old version (due to not defining any scopes), so I decided to rebuild them with the latest codegen.

### CODE REVIEW

**Comment by bjwatson** [comment]
@ethanbao I just noticed this stale PR for Monitoring testing: https://github.com/googleapis/api-client-staging/pull/63

It's out-of-date, so it's not obvious what changes we made in it. Could you take a look?

**Comment by bjwatson** [comment]
Thanks @geigerj. I'm just waiting for @ethanbao to look at the tests portion.

**Comment by ethanbao** [comment]
LGTM. I am going to drop that stale PR.

**Comment by lukesneeringer** [comment]
LGTM.

**Comment by bjwatson** [comment]
Thanks @ethanbao

**Pull request merged**
