### PR TITLE
Update Java staging clients with latest googleapis

### PR DESCRIPTION
**Pull request by shinfan**
Toolkit synced to commit 0f6bffced79713638a5128f783007c8e88cb37be

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Hmm I kind of want to separate out googleapis changes from toolkit changes. Could you do one of the following?

1. Do this regeneration from an older version of googleapis
2. Do a separate regeneration before this one (based on a previous toolkit version) which includes the updates from googleapis, get it submitted, then rebase this PR.

**Comment by shinfan** [comment]
@garrettjonesgoogle  I will pick option#1 to use an older version of googleapis

**Comment by shinfan** [comment]
@garrettjonesgoogle  PTAL

**Comment by shinfan** [comment]
Updated to use 0.1.1 grpc gen packages and all the tests passed.

**Comment by garrettjonesgoogle** [comment]
LGTM

**Pull request merged**
