### PR TITLE
Auto-generate Python Bigtable and Datastore

### PR DESCRIPTION
**Pull request by bjwatson**

### CODE REVIEW

**Comment by bjwatson** [comment]
@tseaver @dhermes I'll publish this once I get approval from @geigerj (although I have been throwing a lot of these at him today).

**Comment by dhermes** [comment]
Nice!

**Comment by bjwatson** [comment]
@geigerj FYI, the common-protos dependency updates I slipped in here for other packages is what I actually published them with.

**Comment by geigerj** [comment]
@bjwatson FYI: there are two more Bigtable services (admin): https://github.com/googleapis/googleapis/tree/master/google/bigtable/admin/v2. Presumably we will also want to wrap them before we call Bigtable "done".

**Pull request merged**
