### PR TITLE
Java: Add logging-external-types

### PR DESCRIPTION
**Pull request by eoogbe**
Updates googleapis/googleapis#187

### CODE REVIEW

**Comment by geigerj** [comment]
This LGTM but @garrettjonesgoogle should give the "real" review; I'm not very familiar with the expected structure of the Java package.

Also, could you add "Updates googleapis/googleapis#187" to the descriptions of your PRs? It adds context and will make it easier to cross reference them in the future.

**Comment by garrettjonesgoogle** [comment]
I'm going to have @michaelbausor review in my stead

**Comment by michaelbausor** [comment]
It looks like we need to include appengine.proto in the gapic yaml (https://github.com/googleapis/googleapis/blob/master/gapic/core/artman_logging_external_types.yaml#L12), since audit_data.proto depends on it for the `UpdateServiceRequest` (and possibly more, I only investigated that far)

**Comment by eoogbe** [comment]
If we follow the dependencies, we need to include the whole `google/appengine/v1` path.

**Pull request closed without merging**
