### PR TITLE
Python: Pubsub regen / bump to 0.15.1

### PR DESCRIPTION
**Pull request by lukesneeringer**
This addresses the PubSub proto changes as well as the missing trailing comma in the proto.

### CODE REVIEW

**Comment by landrito** [comment]
I'd hold off on regen until https://github.com/googleapis/googleapis/pull/263 is merged.

**Comment by lukesneeringer** [comment]
Ah, I did not realize that the YAML changes were not made yet. :-(

**Comment by lukesneeringer** [comment]
@landrito It looks like googleapis/googleapis#263 only affects the GAPIC packages, not the proto packages. Can you confirm this? (I have a semi-urgent need to get a new proto package out ASAP.)

**Comment by landrito** [comment]
Yep, https://github.com/googleapis/googleapis/pull/263 only affects gapic packages.

**Comment by lukesneeringer** [comment]
Thanks. Closing this and making a proto only PR. I can circle back to the GAPIC later.

**Pull request closed without merging**
