### PR TITLE
java: update build.gradle and add video-intelligence

### PR DESCRIPTION
**Pull request by pongad**
The build.gradle change reflects googleapis/toolkit#1382.

Generated Code:
Dependency changes are described in GoogleCloudPlatform/google-cloud-java#2171

Changes to Java code
- removing retry to UNAVAILABLE described in GoogleCloudPlatform/google-cloud-java#2171
- LRO change described in GoogleCloudPlatform/google-cloud-java#2164.

The rest are changes to generated protobuf classes introduced by updating `protoc` to v3.3.0

### CODE REVIEW

**Comment by pongad** [comment]
Java CI is failing because we need to update gax dependency, but we should merge this so I can release new protos, which is required for updating gax.

**Comment by garrettjonesgoogle** [comment]
There is an enormous number of changes included in this PR. Is there any way to split things up, or at least give an overview in the description of what kind of changes this includes?

**Comment by pongad** [comment]
@garrettjonesgoogle PTAL

**Comment by garrettjonesgoogle** [comment]
LGTM

**Pull request merged**
