### PR TITLE
Longrunning updates

### PR DESCRIPTION
**Pull request by bjwatson**
Fix directory name to match package name, and bump version number due to a boneheaded mistake I made.

### CODE REVIEW

**Comment by geigerj** [comment]
What was the change? I see that the directory in `api-client-staging` was wrong (missed that in my last review), but has the package itself changed at all?

**Comment by bjwatson** [comment]
Just a directory name change. No package change apart from the version bump.

**Comment by geigerj** [comment]
Ok -- I don't think that needs a version bump, then. But LGTM.

**Comment by bjwatson** [comment]
The version bump was because I burned `0.11.1` due to a mistake in publishing to PyPI.

**Pull request merged**
