### PR TITLE
java: update generated code

### PR DESCRIPTION
**Pull request by pongad**
reflects googleapis/toolkit#1153 .

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
LGTM

**Comment by garrettjonesgoogle** [comment]
I take it back, the GAX dependency needs to be updated to 0.8.0.

**Comment by pongad** [comment]
I keep forgetting this repo has a build system. Done.

@garrettjonesgoogle PTAL

**Comment by garrettjonesgoogle** [comment]
LGTM

**Pull request merged**
