### PR TITLE
Java: Regenerating for gax-httpjson

### PR DESCRIPTION
**Pull request by garrettjonesgoogle**

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
Note: Java will fail because gax hasn't been published yet at the referenced versions

**Comment by andreamlin** [comment]
There's a diff in Spanner.proto. Does the version number have to be bumped?

**Comment by garrettjonesgoogle** [comment]
Ugh that just kind of snuck in between regenerations. I'll revert that part. Good catch!

**Comment by garrettjonesgoogle** [comment]
I regenerated with the toolkit update in the toolkit PR, and undid the spanner updates. PTAL

**Comment by garrettjonesgoogle** [comment]
Updated with a couple more changes - sorry!

**Pull request merged**
